/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Acceuil (void);
GtkWidget* create_Gestion (void);
GtkWidget* create_Ajouter (void);
GtkWidget* create_Modifier (void);
GtkWidget* create_Afficher (void);
GtkWidget* create_supprimer (void);
