/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Acceuil;
  GtkWidget *Gestion;
  GtkWidget *Ajouter;
  GtkWidget *Modifier;
  GtkWidget *Afficher;
  GtkWidget *supprimer;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Acceuil = create_Acceuil ();
  gtk_widget_show (Acceuil);
  Gestion = create_Gestion ();
  gtk_widget_show (Gestion);
  Ajouter = create_Ajouter ();
  gtk_widget_show (Ajouter);
  Modifier = create_Modifier ();
  gtk_widget_show (Modifier);
  Afficher = create_Afficher ();
  gtk_widget_show (Afficher);
  supprimer = create_supprimer ();
  gtk_widget_show (supprimer);

  gtk_main ();
  return 0;
}

